### ISSUE TITLE
backup_questions_attempt_data_trait is not available before Moodle 3.8

### ISSUE THREAD

**Issue by gormster** [moodleou/moodle-report_embedquestion#5] opened 2020-07-02 01:25 UTC
Your plugin is listed as being compatible with 3.6+, but causes courses to fail backups in versions before 3.6. Wrapping the backup class in a trait_exists check is not enough - moodle assumes that, if the file exists, a class is defined within it.

To me, the simple thing to do is just backport the trait from 3.8 and include it if it doesn't already exist. I've patched this on my server, it seems to work just fine, but I haven't been able to test it thoroughly.

**Comment by timhunt** [comment] 2020-07-02 11:43
This is a duplicate of issue #2. Closing this.

**Closed as completed by timhunt** 2020-07-02 11:43 UTC
